name: journal_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.18.0
  flutter_secure_storage: ^9.1.1
  flutter_local_notifications: ^17.0.0
  top_snackbar_flutter: ^3.3.0
  app_settings: ^5.1.1
  path_provider: ^2.1.1
  dio: ^5.9.0
  open_file: ^3.5.10
  url_launcher: ^6.3.2
  universal_html: ^2.3.0
  workmanager: ^0.9.0
  connectivity_plus: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
